### ISSUE TITLE
Extension doesn't work on latest VS Code release 1.20.1

### ISSUE THREAD

**Issue by RichardMisiak** [Microsoft/vscode-tslint#324]
- tslint Version:  1.0.27
- typescript Version: 2.7.1, 2.4.2
- vscode Version: 1.20.1

Steps to Reproduce:

1. Open VS Code 1.20.1
1. View dev tools/console
```
Activating extension `eg2.tslint` failed:  Cannot find module 'vscode-languageclient'
```

```
[Extension Host] Here is the error stack:  Error: Cannot find module 'vscode-languageclient'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\misr\.vscode\extensions\eg2.tslint-1.0.27\out\extension.js:14:33)
	at Object.<anonymous> (C:\Users\misr\.vscode\extensions\eg2.tslint-1.0.27\out\extension.js:392:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
```

**Comment by egamma** [comment]
I cannot reproduce this and it looks like incomplete install of the extension and I suspect that the update to 1.0.27 failed somehow. Can you pls zip up the folder C:\Users\misr\.vscode\extensions\eg2.tslint-1.0.27 and attach it to the issue.

As a work around can you delete this folder and re-install tslint again.

**Comment by RichardMisiak** [comment]
Reinstalling the extension worked.
Attached is my original installed version of 1.027

[eg2.tslint-1.0.27.zip](https://github.com/Microsoft/vscode-tslint/files/1730598/eg2.tslint-1.0.27.zip)

**Comment by egamma** [comment]
In your installed several node_modules are missing.
![image](https://user-images.githubusercontent.com/172399/36300975-9846cfa6-1303-11e8-8e3f-ca2c7c1bffe8.png)

I´ve file an issue in the vscode repository and close this issue.

**Comment by egamma** [comment]
One more thing can you please attach the log for the shared process to Microsoft/vscode#43813?

This is the log 
![image](https://user-images.githubusercontent.com/172399/36314318-b87e0d62-1334-11e8-9b47-b678eaf44e5d.png)
