### ISSUE TITLE
0.6.6 - problem.getFix is not a function

### ISSUE THREAD

**Issue by ValeryVS** [Microsoft/vscode-tslint#143]
I encounter the error
`vscode-tslint: 'problem.getFix is not a function'`
after update to 0.6.6

My project use
`tslint: "3.13.0" `

**Comment by caiusCitiriga** [comment]
Same problem here, after the last update to 0.6.6 on my iMac and MBP (both running macOS Sierra) I get this annoying problem.

**Comment by ValeryVS** [comment]
I downgrade version to 0.6.5 for now.
Not shure is there a simier way to to this, but there in instruction
https://code.visualstudio.com/Docs/editor/extension-gallery#_common-questions

* uninstall
* download 0.6.5
https://eg2.gallery.vsassets.io/_apis/public/gallery/publisher/eg2/extension/tslint/0.6.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
* install from vsix

**Comment by michastreppel** [comment]
I have the same problem. When hoovering over the error message I get sometimes the following 
(partial) stacktrace.
![error](https://cloud.githubusercontent.com/assets/7882186/20749513/edfda1a4-b6f2-11e6-9856-8a6d3375bd31.png)

**Comment by egamma** [comment]
I see the problem, auto fixing is only available in tslint 4. I'll work on a fix as soon as possible. Sorry for the hickup.

**Comment by egamma** [comment]
Published the fix in 0.6.7.

Actually auto fixing appeard in version 3.15.0 of tslint, so another workaround would be to upgrade to 3.15.0.
